[tool.poetry]
name = "sweetheart"
version = "0.1.1b1"
description = "get coding full power from scratch including AI"
authors = ["Nicolas Champion <champion.nicolas@gmail.com>"]
license = "CECILL-C"
readme = "README.md"
repository = "https://github.com/IncredibleProgress/sweetheart.py"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
